two_app/urls.py
from allauth.account.views import LogoutView
from django.urls import path
from . import views

app_name = 'two_app'


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('accounts/login/', views.ShopLogin.as_view(), name='shop-signup'),
    path('accounts/login-customer/<slug:shop_name>/<uuid:shopId>/', views.customer_login, name='customer-login'),
    path('accounts/shop/shop-name-create/<uuid:shopId>/', views.shopNameCreate, name='shop-name-create'),
    path('accounts/shop/<uuid:shopId>/', views.shopProfile, name='shop-profile'),
    path('accounts/customer/<slug:shop_name>/<uuid:shopId>/', views.customer_profile, name='customer-profile'),
    path('accounts/account_logout/', LogoutView.as_view(), name='account_logout'),
]

twologin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('two_app.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

two_app/models.py
from uuid import uuid4
from django.db import models
from django.utils import timezone
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager
import allauth
from allauth.socialaccount.models import SocialLogin
from allauth.account.utils import get_next_redirect_url
from allauth.utils import get_request_param


@classmethod
def state_from_request(cls, request):
    state = {}
    next_url = get_next_redirect_url(request)
    # add this statement is important. We get the query parameter we added to the template and store it here as a  session value.
    try:
        request.session["user_type"] = get_request_param(request, "user", None)
    except KeyError:
        print('user_type is not exist')

    try:
        request.session["shop_name"] = get_request_param(request, "shop_name", None)
    except KeyError:
        print('shop_name is not exist')

    try:
        request.session["shop_id"] = get_request_param(request, "shop_id", None)
    except KeyError:
        print('shop_id is not exist')

    if next_url:
        state["next"] = next_url
    state["process"] = get_request_param(request, "process", "login")
    state["scope"] = get_request_param(request, "scope", "")
    state["auth_params"] = get_request_param(request, "auth_params", "")

    return state

allauth.socialaccount.models.SocialLogin.state_from_request = state_from_request




class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('mail address is required')

        email = self.normalize_email(email)
        user = self.model(username=username, email=email)

        user.set_password(password)
        user.save(using = self._db)

        return user

    def create_superuser(self, username, email, password):

        user = self.create_user(username, email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class CustomUser(AbstractBaseUser):
    userId = models.CharField(
        max_length=255, default=uuid4, primary_key=True, editable=False, unique=True)
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(unique=True)
    created = models.DateTimeField(default=timezone.now)

    is_shop = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)

    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    def has_module_perms(self, app_label):
        return self.is_superuser

    def has_perm(self, perm, obj=None):
        return self.is_superuser


class Shop(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    shop_name = models.SlugField(max_length=255, blank=True)
    shopId = models.UUIDField(
        default=uuid4, editable=True, unique=True, blank=False)

    def __str__(self):
        return self.user.email


class Customer(models.Model):
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.user.email

two_app/forms.py
from django import forms
from two_app.models import Shop


class ShopNameForm(forms.ModelForm):
    class Meta:
        model=Shop
        fields = ['shop_name']

        widgets = {
            'shop_name': forms.TextInput(attrs={'size':'40'}),
        }

two_app/views.py
from allauth.account.views import LoginView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from two_app.forms import ShopNameForm
from two_app.models import CustomUser, Shop, Customer


class HomeView(LoginView):
    template_name = "two_app/index.html"

    # Retrieve all objects in Shop and list them on template.
    def get(self, request, *args, **kwargs):
        shops = Shop.objects.all()
        context = {
            'shops':shops
        }

        return render(request, self.template_name, context)


class ShopLogin(LoginView):
    template_name = 'two_app/shop-login.html'


def customer_login(request, shop_name, shopId):
    shop = get_object_or_404(Shop, shopId=shopId)

    context = {
        "shop":shop
    }

    return render(request, 'two_app/customer-login.html', context)


@login_required(redirect_field_name=None)
def shopProfile(request, shopId):

    user=request.user

    # This is Route guard.
    shop = get_object_or_404(Shop, user__email=user.email)
    # Exclude Shop user that come from other shop profiles and Customer users coming from the customer side
    if not shop.shopId == shopId or Customer.objects.filter(user__email=user.email).exists():
        return redirect('two_app:home')

    form = ShopNameForm()

    # Check if the current user is in the Shop model.
    # If not, add the content of the "no comment" here.
    if Shop.objects.filter(user__email=user.email).exists():
        text = Shop.objects.filter(user__email=user.email).values_list('description', flat=True).get()
    else:
        text = "no comment"

    context = {
        'shop': shop,
        'text': text,
        'form': form
    }

    template = "two_app/shop-profile.html"

    return render(request, template, context)


# This view is for creating a shop name.
# Only the variation part of the form is separated from the above view,
@login_required
def shopNameCreate(request, shopId):

    # Auth guard
    # following code is to prevent customer users from accessing this view directly.
    if Customer.objects.filter(user__email=request.user.email).exists():
        return redirect('two_app:home')

    form = ShopNameForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            shop_name = form.cleaned_data['shop_name']
            shop = Shop.objects.filter(user=request.user).get()
            shop.shop_name = shop_name
            shop.save()

            context = {
                "shop":shop
            }

        # Important: Replace the form part entirely with success.html.
        if request.htmx:
            return render(request, 'two_app/success.html', context)
    else:
        form = ShopNameForm()
        context = {
            "form": form,
        }

    return render(request, 'two_app/shop-profile.html', context)





@login_required(redirect_field_name=None)
def customer_profile(request, shop_name, shopId, *args, **kwqrgs):

    user=request.user
    shop_name_session = request.session["shop_name"]
    shop_id_session = request.session["shop_id"]

    # This is Auth guard.
    # Exclude come from other customer profiles and if there is an object in the shop model.
    if not shop_name_session==shop_name \
            or shop_id_session==shopId \
            or Shop.objects.filter(user__email=user.email).exists():

        return redirect('two_app:home')

    customer = get_object_or_404(Customer, user__email=user.email)

    context = {
        'customer':customer
    }
    template = "two_app/customer-profile.html"
    return render(request, template, context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/base-style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom-style.css' %}">
    <title>Auth App</title>
</head>
<body>
    <section class="wrapper">
        <header class="header">
            <div class="header__contents">
                <a class="header__link" href="{% url 'two_app:home' %}">Home</a>
            </div>
        </header>
        {% block contents %}
        {% endblock %}
    </section>
    <script src="{% static 'js/htmx.min.js' %}" defer></script>
</body>
</html>

templates/two_app/customer-login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% block contents %}

    <section class="signin">
       <form class="signin__form">
        <h1 class="signin__form__title">Customer Sign-in</h1>
           <div>Shop name is: {{ shop.shop_name }}</div>
           <div>Shop ID is: {{ shop.shopId }}</div>
            <a class="signin__form__button"
               href="{% provider_login_url 'google' user='customer' shop_name=shop.shop_name shop_id=shop.shopId action='reauthenticate' %}"
               class="btn btn btn-danger btn-lg btn-block"
               role="button" aria-pressed="true">
                <h2>Sign in with Google</h2>
            </a>
        </form>
    </section>
    <div>{{ user_e }}</div>

{% endblock %}

templates/two_app/customer-profile.html
{% extends 'base.html' %}
{% block contents %}

    <section class="profile">

        {% if messages %}
            <div class="message">
                <strong>Messages:</strong>
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% if user.is_authenticated %}
            <div class="profile__contents">
                <p>Welcome, {{ customer.user.email }}</p>
                <p>{{ customer.description }}</p>
            </div>
        {% else %}
            <div class="profile__contents">
                <p>Welcome Friend, please log in</p>
            </div>
        {% endif %}

        {% if user.is_authenticated %}
            <div class="profile__logout">
                <a href="javascript:{document.getElementById('logout').submit()}">Logout</a>
                <form action="{% url 'two_app:account_logout' %}" id="logout" method="POST">
                    {% csrf_token %}
                    <input type="hidden">
                </form>
            </div>
        {% else %}
            <div class="profile__logout">
                <h2>Not login</h2>
            </div>
        {% endif %}

    </section>

{% endblock %}

templates/two_app/index.html
{% extends 'base.html' %}
{% block contents %}
    <main class="main">

        <section class="title">
            <h1>Resavation system platform</h1>
        </section>

        {% if messages %}
            <section class="message">
                <div class="alert alert-primary" role="alert">
                    <strong>Messages:</strong>
                    {{ message }}
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </div>
            </section>
        {% endif %}

        <section class="login">
            <div class="login__card">
                <h2 class="login__title">Shop Login</h2>
                <div class="login__button">
                    <a href="{% url 'two_app:shop-signup' %}">
                        <div class="login__card__body">
                            <h2 class="login__card__title">Shop Login Button</h2>
                        </div>
                    </a>
                </div>
            </div>
            <div class="login__shop">
                <h2>Shop List</h2>
                {% for shop in shops %}
                    <div class="login__shop__item">
                        <h3 class="login__shop__name">Shop Name: {{ shop.shop_name }}</h3>
                        <div class="login__shop__shopid">UUID: {{ shop.shopId }}</div>
                        {% if shop.shop_name %}
                        <div class="login__shop__link">
                            <a href="{% url 'two_app:customer-login' shop.shop_name shop.shopId %}">http://127.0.0.1:8022/accounts/login-customer/{{ shop.shop_name }}/{{ shop.shopId }}</a>
                        </div>
                        {% endif %}
                    </div>

                {% endfor %}
            </div>
        </section>
        <section class="text_message">
            {% if user.is_authenticated %}
                <p>Welcome, {{ user.email }}</p>
            {% else %}
                <p>Welcome Friend, please log in</p>
            {% endif %}
        </section>

    </main>
{% endblock %}

templates/two_app/shop-login.html
{% extends 'base.html' %}
{% load socialaccount %}
{% block contents %}

    <div class="signin">
        <form class="signin__form">
            <h1 class="signin__form__title">Shop Sign-in</h1>
            <a class="signin__form__button" href="{% provider_login_url 'google' action='reauthenticate' user='shop' %}">
                <h2>Sign in with Google</h2>
            </a>
        </form>
    </div>
    <div>{{ user_e }}</div>

{% endblock %}

templates/two_app/shop-profile.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block contents %}

    <section class="profile">

        {% if messages %}
            <div class="message">
                <strong>Messages:</strong>
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        {% if user.is_authenticated %}
            <div class="profile__contents">
                <div class="profile__title">
                    <h1>Welcome, {{ shop.user.email }}</h1>
                    <h2>{{ text }}</h2>
                    <div class="shop__uuid">Your uuid: {{ shop.shopId }}</div>
                </div>
            {% if shop.shop_name %}
                {% include "two_app/success.html" %}
            {% else %}
                <div class="shop__form">
                    <form method="POST" hx-post="{% url 'two_app:shop-name-create' shop.shopId %}" hx-swap="outerHTML"
                          hx-target="this" class="shop__dialog">
                        {% csrf_token %}
                        <div id="shop__error"></div>
                        <div class="shop__text">Please input your shop name!</div>
                        <label>{{ form.shop_name.label_tag }}</label>
                        {% render_field form.shop_name class="shop__name" %}
                        <div class="shop__button">
                            <button type="submit" class="shop__button__submit">Submit</button>
                        </div>
                    </form>
                </div>
            {% endif %}
            <div>
            </div>
        {% else %}
            <div class="profile__contents">
                <p>Welcome Friend, please log in</p>
            </div>
        {% endif %}

        {% if user.is_authenticated %}
            <div class="profile__logout">
                <a href="javascript:{document.getElementById('logout').submit()}">Logout</a>
                <form action="{% url 'two_app:account_logout' %}" id="logout" method="POST">
                    {% csrf_token %}
                    <input type="hidden">
                </form>
            </div>
        {% else %}
            <div class="profile__logout">
                <h2>Not login</h2>
            </div>
        {% endif %}

    </section>

{% endblock %}

templates/two_app/success.html
<div class="success">
        <div class="success__name">Shop Name: {{ shop.shop_name }}</div>
        <div class="success__button"><a href="{% url 'two_app:customer-login' shop.shop_name shop.shopId %}">http://127.0.0.1:8022/accounts/login-customer-neo/{{ shop.shop_name }}/{{ shop.shopId }}</a></div>
    </div>
</div>